# This is a basic workflow to help you get started with Actions

name: crossLib CI

on:
  push:
    branches:
    - master
    - release/*
jobs:
  # This workflow downloads dependencies and compiles the test application
  test:
    name: crossLib CI
    runs-on: ubuntu-18.04
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Installs the necessary dependencies 
    - name: Install packages
      run: bash ./cross_apis_r/packages.sh true

    # Start compiling test program in multiple configurations
    - name: Compiling test program for linux
      run: |
        echo Compiling for linux...,
        bash ./cross_apis_r/compile.sh linux 64 --actions-build
    - name: Compiling test program for windows
      run: |
        echo Compiling for windows...,
        bash ./cross_apis_r/compile.sh win32 64 --actions-build
        echo Compiling for windows x32...
        bash ./cross_apis_r/compile.sh win32 32 --actions-build
